name: Monitor de Incendios Paxban
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora autom치ticamente
  workflow_dispatch:      # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests shapely

      - name: Ejecutar detector de incendios
        run: python actualizar_paxban.py

      - name: Actualizar Repositorio
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add incendios.json
          git commit -m "Actualizaci칩n de incendios en Paxb치n" || exit 0
          git push
