name: Monitor y Deploy Paxban
on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 * * * *'
    - cron: '0 13 * * *' # Reporte diario 7:00 AM Guatemala (13:00 UTC)
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

# Esto evita el error de "Multiple artifacts" y "In progress deployment"
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  monitor-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar GEOS
        run: sudo apt-get update && sudo apt-get install -y libgeos-dev

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Configurar Destinatarios y Modo
        run: |
          # Definir listas de correos
          EMAILS_ALERTAS="forestal@gibor.com, regencia@gibor.com, coradojose952@gmail.com"
          EMAIL_MANUAL="coradojose952@gmail.com"
          
          # Lógica de selección según el evento que disparó el flujo
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Modo: Manual (Solo a Corado)"
            echo "RECIPIENT_EMAIL=$EMAIL_MANUAL" >> $GITHUB_ENV
            echo "FORCE_REPORT=true" >> $GITHUB_ENV
          elif [[ "${{ github.event.schedule }}" == "0 13 * * *" ]]; then
            echo "Modo: Reporte Diario 7:00 AM (A todos)"
            echo "RECIPIENT_EMAIL=$EMAILS_ALERTAS" >> $GITHUB_ENV
            echo "FORCE_REPORT=true" >> $GITHUB_ENV
          else
            echo "Modo: Monitoreo Automático (A todos, solo si hay fuego)"
            echo "RECIPIENT_EMAIL=$EMAILS_ALERTAS" >> $GITHUB_ENV
            echo "FORCE_REPORT=false" >> $GITHUB_ENV
          fi

      - name: Ejecutar Detector de Incendios
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python actualizar_paxban.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
